### ISSUE TITLE
Parsing with DateFormat Infrastructure

### ISSUE THREAD

**Issue by jordancluts** [JuliaTime/NanoDates.jl#1]
I have a goal of being able to parse dates in a string using this package as simply as the Base Dates functionality. That means using a simple DateFormat spec. Also hopefully we can piggyback on Dates infrastructure as much as possible.

`NanoDate("2020-05-03T12:59:58.123456789",dateformat"yyyy-mm-ddTHH:MM:SS.s")` should work properly.

I have found that I am able to accomplish this quite easily.

I have made the following demonstration at the REPL. First however one must make NanoDate a subtype of Dates.AbstractDateTime by editing nanodate.jl file and then `dev` the modified package.

```
struct NanoDate <: Dates.AbstractDateTime
    datetime::DateTime      # DateTime(UTM(microsec))
    nanosecs::Nanosecond    # Nanosecond(microsecond * 1_000 + nanosecond)

    function NanoDate(datetime::DateTime, nanosecs::Nanosecond)
        nanos = value(nanosecs)
        0 <= nanos < 1_000_000 && return new(datetime, nanosecs)

        datetime2, nanosecs2 = safe_canonical(value(datetime), nanos)
        new(datetime2, nanosecs2)
    end
end
```

Next run the following lines at the REPL
```
julia> NanoDates.NanoDate(dt::AbstractString, df::DateFormat=ISODateTimeFormat) = parse(NanoDate, dt, df)

julia> Dates.CONVERSION_SPECIFIERS['n'] = Nanosecond
Nanosecond

julia> Dates.CONVERSION_TRANSLATIONS[NanoDate] = (Year,Month,Day,Hour,Minute,Second,Nanosecond,Dates.AMPM)
(Year, Month, Day, Hour, Minute, Second, Nanosecond, Dates.AMPM)

julia> @inline function Dates.tryparsenext(d::Dates.DatePart{'n'}, str, i, len)
      val = Dates.tryparsenext_base10(str, i, len, Dates.min_width(d), Dates.max_width(d))
      val === nothing && return nothing
      ns0, ii = val
      len = ii-i
      ns = ns0 * Int64(10) ^ (9 - len)
      return ns, ii
  end

julia> function NanoDate(yr,mn=1,dy=1,hr=0,mi=0,sc=0,ns=0,ampm::Dates.AMPM=Dates.TWENTYFOURHOUR)
              hr = Dates.adjusthour(hr,ampm)
              NanoDate(DateTime(yr,mn,dy,hr,mi,sc,0),NanoDates.nanosecs(ns))
          end
```

These lines
- Define a function to parse the NanoDate using Dates internals
- Define the Nanosecond indentifier
- Set the required NanoDates fields for Dates to send to the constructor
- Creates a function to handle the Nanosecond identifier
- Creates a new constructor to create a NanoDate from the Dates parsing output.

Once this is complete parsing works. With the exception that one must replace 's' characters after the decimal with 'n' characters in the DateFormat.

```
julia> NanoDate("2020-05-03T12:59:58.123456789",dateformat"yyyy-mm-ddTHH:MM:SS.n")
2020-05-03T12:59:58.123456789

julia> NanoDate("093522.1275  03/05/2020",dateformat"HHMMSS.nnnn  mm/dd/yyyy")
2020-03-05T09:35:22.127500

julia> NanoDate("2020-05-16T05:59:59.123456789PM",dateformat"yyy-mm-ddTHH:MM:SS.nnnnnnnnnp")
2020-05-16T17:59:59.123456789
```

While this method works and a PR could be made I thought it was likely that a few changes would be needed before we would be happy. 
- The constructor is a bit odd, it may be better to define a few other NanoDate specific methods (to override the Dates defaults) that will handle the parsing a bit more intelligently. These could handle things more cleanly and not require a "weird" constructor for this to work.
- Defining some of those internals to handle things more cleanly would also aid in compatibility. With the above using the 's' millisecond identifier doesn't cause an error but throws away all subsecond data. Customizing some more internals would probably be needed to fix this
 ```
julia> NanoDate("2020-05-16T12:59:59.123",dateformat"yyy-mm-ddTHH:MM:SS.sss")
2020-05-16T12:59:59
```
- We'd probably want to define a new "default" format to replace "ISODateTimeFormat". This would likely just be `const ISONanoDateFormat = DateFormat("yyyy-mm-dd\\THH:MM:SS.n")` and use that as the default parse target.

That said this is nice in that it requires no type piracy, just a few method definitions, and adding NanoDates identifiers to the Dates "database". These databases are specifically marked to be allowed to be expanded by other Date Types. It does rely on Dates internals, I'm not sure what the guarantees are on that. The comments do indicate a desire to allow other date types to hook into the machinery.

**Comment by JeffreySarnoff** [comment]
NanoDate had been an AbstractDateTime -- that must have been erased without intent.
This is very helpful.   I am liking the asity.

**Comment by JeffreySarnoff** [comment]
I just ran your functions + examples.  This is very close to the way I had expected things to work.
I had been encountering some strange outcomes ... now I understand this had a cause,
the erasure of NanoDate <: AbstractDateTIme.  The difficulty with Dates' handling of 's' is 
(a) it is nonuniform, sometimes one 's' gets all 9 subsecond digits, sometimes it limits the 
vacuuming to the the most significant millisecond digit (and then, 2 '"ss" get the first two digits).
(b) if one puts a separator between the 's's, "10.234_567_890" and uses that with dateformat"...SS.s_s_s",
the millisecond digits are found three times and the microsecond, nanosecond digits are not found.

I have had some luck with requiring "sss" be used with NanoDates (and not one or two 's's) for
getting all the subsecond digits usefully found -- there is a restriction, they must follow seconds
immediately after the '.' "_SS.sss" other patterns run into the low level nonuniform handling of 's'.

This saves us a bunch of time!

**Comment by jordancluts** [comment]
Based on my perusing of the code today it will be very difficult (using Dates machinery) to get a format like "SS.s_s_s" to work. The tokenizer and parser in Dates is just not set up to have "mid-value" separators. Only separators *between* values.
One could define a new identifier for each grouping.
- 's' -> Millisecond (as it currently is)
- 'u' -> microsecond
- 'n' -> nanosecond

then a format like "SS.sss_uuu_nnn" would be very easy with a `tryparsenext` for each of them (that would all be basically identical). The disadvantage is that if you *don't* have separators you are forced to have all the letters so parsing "59.123456789" would require "SS.sssuuunnn" which is less convenient than "n", "s" or even "sssssssss" or "nnnnnnnnn"

**Comment by JeffreySarnoff** [comment]
I concur.  Using 'n' is least objectionable and appears to be the path that introduces least hassle for clients.
'u' is not available to us

**Comment by jordancluts** [comment]
While perusing the Dates issue label I discovered [this issue.](https://github.com/JuliaLang/julia/issues/37579) It seems that the approach I showed here is more or less what AstroTime.jl does (or did in Oct. 2020 anyway). Perhaps we should investigate how they have plumbed things in and out. There may even be a way to coordinate and reduce duplication of effort but that seems less likely.

**Comment by JeffreySarnoff** [comment]
AstroTime.jl is very good -- excellent for astronomical time interworkings.  I spoke with Helge a couple of times during the design.

**Comment by JeffreySarnoff** [comment]
Now that you have looked at this from multiple avenues, what approach do you feel will work best and work well?

**Comment by jordancluts** [comment]
Apologies for the delay, other obligations took my attention for a few days.

I think that we should hook into the Dates functionality as much as possible by doing what I have described above. The vast majority of the needed code (and there are in fact some parts missing because I didn't account for output formatting) can be lifted from Astrotime.jl with some modifications for our needs. Astrotime uses 'f' instead of 'n' an argument could be made to copy them (and use the same registered name) to aid in the packages working together better.

We arrive however at a problem which is what to do if a user calls NanoDate("sometime.123",dateformat"SS.sss"). Since this date/time has only 3 trailing digits the dateformat is valid and will parse correctly. But we have a problem in creating a constructor that can properly handle this case. I.E. distinguishing these two hypothetical constructors:
`NanoDate(Year::Int,Month::Int,Day::Int,Hour::Int,Minute::Int,Second::Int,Millisecond::Int,ampm::Dates.AMPM)`
`NanoDate(Year::Int,Month::Int,Day::Int,Hour::Int,Minute::Int,Second::Int,Nanosecond::Int,ampm::Dates.AMPM)`

the data returned from Dates doesn't allow us to distinguish these two cases. The raw parsing in Dates.jl is ultimately performed inside of `Dates.tryparsenext_core`
```
julia> Dates.tryparsenext_core("2020-05-16T12:59:59.123",1,23,dateformat"y-m-dTH:M:S.n")
((2020, 5, 16, 12, 59, 59, 123000000), 24, 7)

julia> Dates.tryparsenext_core("2020-05-16T12:59:59.123",1,23,dateformat"y-m-dTH:M:S.s")
((2020, 5, 16, 12, 59, 59, 123), 24, 7)
```

The tuple of data is ultimately what is splatted into the constructor.

To fix this we would define a specific parse function that can handle the ambiguity

```
function Base.parse(::NanoDate, str::AbstractString, df::DateFormat=default_format(T)) where T<:TimeType
    pos, len = firstindex(str), lastindex(str)
    val = tryparsenext_internal(T, str, pos, len, df, true)
    @assert val !== nothing
    values, endpos = val
    
    if Dates.DatePart{'s'} in df
        return NanoDate_millisecond_constructor(values...)
    else
       return NanoDate_nanosecond_constructor(values...)
    end
end
```

This would work and perhaps should be the method for now.
A *better* solution however would be to make the Dates machinery tell us what it has! The `tryparsenext_internal` and `tryparsenext_core` functions are `@generated` so I don't particularly understand them, but at some point the code knows which value (year, month, day, second, millisecond, etc.) the integers correspond to. Why can't it tell us what it is handing back?
I *think* it would be a non-breaking change to return instead a named tuple so the result from `tryparsenext_core` would look like this instead.

```
Dates.tryparsenext_core("2020-05-16T12:59:59.123",1,23,dateformat"y-m-dTH:M:S.n")
((year=2020,month= 5,day= 16,hour= 12,minute= 59,second= 59,nanosecond= 123000000), 24, 7)
```

The default constructor Dates uses (splatting the tuple into the constructor) would work exactly the same. But custom date types with an alternate `parse` function could use the data in the named tuple to handle more complex cases easily.

**Comment by JeffreySarnoff** [comment]
```
julia> using Dates, NanoDates
julia> nd = NanoDate(2022, 6, 18,  12, 15, 30,  123, 456, 789)
2022-06-18T12:15:30.123456789

julia> df = dateformat"-- sssss HH:MM:SS yyyy-mm-dd";
julia> NanoDate(nd, df)
"-- 12345 12:15:30 2022-06-18"

julia> NanoDate(ans, df)
2022-06-18T12:15:30.123450
```
