### ISSUE TITLE
parse DateTime format without digits

### ISSUE THREAD

**Issue by kafisatz** [JuliaTime/NanoDates.jl#21]
Hi

I am working with InfluxDB, reading and writing timestamps with different precisions: ns, us, ms, s

I am using your package to parse the string response to NanoDates.
When I use seconds precision I get a string of the following format:
```
2019-05-02T16:12:41Z

#works
NanoDate("2022-05-24T10:43:22.350Z")
2022-05-24T10:43:22.350

#fails, but why?
julia> NanoDate("2022-05-24T10:43:22Z")
ERROR: ArgumentError: 2022-05-24T10:43:22Z needs its own dateformat.

```

The NanoDate constructor fails on this string.
I think this is the [ISO8061 UTC] timestamp (as per your docs)

**Comment by JeffreySarnoff** [comment]
This is an oversight. The internal formats should
include dateformat"yyyy-mm-ddTHH:MM:SSZ" (and does soonish).

The message "ArgumentError: 2022-05-24T10:43:22Z needs its own dateformat."
wants you to do this:
```
julia> using Dates, NanoDates

julia> const FormatSecsUTC = dateformat"yyyy-mm-ddTHH:MM:SSZ"
dateformat"yyyy-mm-ddTHH:MM:SSZ"

julia> utc_string = "2022-05-24T10:43:22Z"
"2022-05-24T10:43:22Z"

julia> utc  = NanoDate(utc_string, FormatSecsUTC)
2022-05-24T10:43:22
```
