### ISSUE TITLE
Parsing of sub-nanosecond precision dates

### ISSUE THREAD

**Issue by anowacki** [JuliaTime/NanoDates.jl#3]
Fantastic to see the package registered!

Parsing dates with more than nine decimal places on the second causes incorrect dates to be returned with the default format:

```julia
julia> using Dates, NanoDates

julia> NanoDate("2000-01-01T00:00:00.123456789") # ns precision: correct date
2000-01-01T00:00:00.123456789

julia> NanoDate("2000-01-01T00:00:00.1234567890") # 0.1 ns precision: wrong date!
2000-01-01T00:00:01.234567890
```

If one tries to use a `DateFormat` with more than nine decimal places, you get a slightly unhelpful message that the string doesn't match the format, when really 10+ decimal places just aren't supported:

```julia
julia> NanoDate("2000-01-01T00:00:00.1234567890", dateformat"yy-mm-ddTHH:MM:SS.ssssssssss")
ERROR: ArgumentError: 2000-01-01T00:00:00.1234567890 does not match dateformat
Stacktrace:
 [1] NanoDate(str::String, df::DateFormat{Symbol("yy-mm-ddTHH:MM:SS.ssssssssss"), Tuple{Dates.DatePart{'y'}, Dates.Delim{Char, 1}, Dates.DatePart{'m'}, Dates.Delim{Char, 1}, Dates.DatePart{'d'}, Dates.Delim{Char, 1}, Dates.DatePart{'H'}, Dates.Delim{Char, 1}, Dates.DatePart{'M'}, Dates.Delim{Char, 1}, Dates.DatePart{'S'}, Dates.Delim{Char, 1}, Dates.DatePart{'s'}}}; localtime::Bool)
   @ NanoDates ~/.julia/packages/NanoDates/rPTb0/src/strings.jl:261
 [2] NanoDate(str::String, df::DateFormat{Symbol("yy-mm-ddTHH:MM:SS.ssssssssss"), Tuple{Dates.DatePart{'y'}, Dates.Delim{Char, 1}, Dates.DatePart{'m'}, Dates.Delim{Char, 1}, Dates.DatePart{'d'}, Dates.Delim{Char, 1}, Dates.DatePart{'H'}, Dates.Delim{Char, 1}, Dates.DatePart{'M'}, Dates.Delim{Char, 1}, Dates.DatePart{'S'}, Dates.Delim{Char, 1}, Dates.DatePart{'s'}}})
   @ NanoDates ~/.julia/packages/NanoDates/rPTb0/src/strings.jl:255
 [3] top-level scope
   @ REPL[38]:1
```

I had a quick look at the code but I apologise that I haven't been able to work out where the issue is coming from yet, so sadly this bug report doesn't come with a PR to fix it.

**Comment by JeffreySarnoff** [comment]
Appreciate the quick look :) N.P.
I am not sure that accepting sub-nanosecond times is a good idea.  There is no infrastructure to support that. 
The handling of nanoseconds is everywhere.  Handling of subnanoseconds would have to be everywhere too.
Also, the smallest period is Nanosecond.  I have thought about finer periods, their support really wants a 128bit underlying type.

**Comment by anowacki** [comment]
Sorry for the confusion.  I didn't mean that NanoDates should support sub-nanosecond precision, but rather that supplying an incorrect `DateFormat` should not cause the `NanoDate` constructor to return an incorrect date.  Instead an error should be thrown.

**Comment by JeffreySarnoff** [comment]
On the gentle_subnanos branch, I added a set of tests to the bottom of the /test/strings.jl file.
The new code and an explanation are found:
https://github.com/JuliaTime/NanoDates.jl/commit/3878003bda122037de9804e1f7c9a2338f7de99f
and
https://github.com/JuliaTime/NanoDates.jl/compare/gentle_subnanos

[I have not yet run this branch alone nor with the new tests it has -- would you?]

**Comment by JeffreySarnoff** [comment]
no need -- I see what is happening

**Comment by JeffreySarnoff** [comment]
The current main, merging, should have you covered. Let me know of others.

**Comment by anowacki** [comment]
Thanks!  I think the behaviour is just as it should be—trailing digits ignored unless a `DateFormat` is provided, in which case an error is thrown.
