### ISSUE TITLE
Typo in nanodate.jl

### ISSUE THREAD

**Issue by hk7797** [JuliaTime/NanoDates.jl#30]
I was going over the nanodate source code and found a typo. In my local branch, i have fixed the code to highlight it. Below screenshot shows git diff results

![image](https://user-images.githubusercontent.com/20927463/220824376-4fd6aaa4-94b3-44d1-9738-3a77273527df.png)

**Comment by JeffreySarnoff** [comment]
Thank you, thank you. I just noticed your note.  Fixing now.

**Comment by JeffreySarnoff** [comment]
pending merge
