### ISSUE TITLE
Error: NanoDate to timestamp to NanoDate

### ISSUE THREAD

**Issue by cemlyn007** [JuliaTime/NanoDates.jl#31]
Good morning, cool package! 

Not sure if I am doing something wildly wrong or if this a bug? It looks like going from NanoDate to timestamp to NanoDate doesn't work for whole second datetimes?
```
nd = NanoDates.NanoDate(Dates.DateTime(2023, 6, 16, 17, 0, 0), 0)
nd_string = NanoDates.timestamp(nd)  # "2023-06-16T17:00:00Z"
NanoDates.NanoDate(nd_string)  # ERROR: ArgumentError: 2023-06-16T17:00:00Z needs its own dateformat.
```

**Comment by cemlyn007** [comment]
If I strip the Z from nd_string before using the NanoDate constructor:
```
nd_string = NanoDates.NanoDate(rstrip("2023-06-16T17:00:00Z", 'Z'))
NanoDates.NanoDate(nd_string)  # 2023-06-16T17:00:00
```

**Comment by cemlyn007** [comment]
If I add 1 nanosecond to my original example:
```
nd = NanoDates.NanoDate(Dates.DateTime(2023, 6, 16, 17, 0, 0), 1)  # 2023-06-16T17:00:00.000000001
nd_string = NanoDates.timestamp(nd)  # "2023-06-16T17:00:00.000000001Z"
NanoDates.NanoDate(nd_string)  # 2023-06-16T17:00:00.001
```

I suspect I am doing something absurd?

**Comment by JeffreySarnoff** [comment]
What you are doing is pushing the package beyond its original design -- in a reasonable manner.
The `timestamp` function is about generating the correct output string, NanoDates is not expected to reparse it.
The way to do this currently is to use `string` (or to strip the trailing 'Z' before reconverting).
```
using Dates, NanoDates

nd = NanoDate(DateTime(2023, 6, 16, 17, 0, 0), 1)
# 2023-06-16T17:00:00.000000001
ndstr = string(nd)
# "2023-06-16T17:00:00.000000001"
nd_recovered = NanoDate(ndstr)
2023-06-16T17:00:00.000000001

# or
ndstamp = timestamp(nd)
# "2023-06-16T17:00:00.000000001Z"
ndstr = ndstamp[1:end-1]
# "2023-06-16T17:00:00.000000001"
nd_recovered = NanoDate(ndstr)
2023-06-16T17:00:00.000000001
2023-06-16T17:00:00.000000001
```

still your last example is not ok, and really the timestamp should be parseable
All this bears some digging .. please notify me if I have not updated this thread in three weeks.
Thank you for noticing.

**Comment by cemlyn007** [comment]
Hi @JeffreySarnoff, thank you! 👍

**Comment by JeffreySarnoff** [comment]
and you get some of the thanks -- too

**Comment by cemlyn007** [comment]
Thanks Jeffrey, sorry I didn't bother you in end, I used a work around and then thought if it wasn't impacting you that I shouldn't waste your time any further!

Anyways hope you had a great summer and thank you very much for an awesome library!
