### ISSUE TITLE
Support nanosecond timestamps (from/to)

### ISSUE THREAD

**Issue by rbeeli** [JuliaTime/NanoDates.jl#44]
If I read the docs correctly, there is no support for constructing a `NanoDate` from a UNIX timestamp in nanoseconds, and also no function to convert a `NanoDate` to an `Int64` representing nanoseconds since epoch.

Is this correct? If so, could support for this be added?

**Comment by rbeeli** [comment]
Ok, I was to fast with my conclusion, it just wasn't clear from the docs, maybe this could be added? It shows something under `"Technical: unexported"`, but `Dates.value` is exported/accessible.

```
julia> NanoDate(2024,7, 7)
2024-07-07T00:00:00

julia> Dates.value(NanoDate(2024,7, 7))
63855993600000000000

julia> NanoDate(63855993600000000000)
2024-07-07T00:00:00
```

Also, there is `nanodate2unixnanos`, but not listed in the docs.

**Comment by rbeeli** [comment]
Actually, these methods do not represent the nanoseconds timestamp since epoch, is this correct?

The nanosecond UNIX timestamp for `2024-07-07` should be `1720310400000000000`, not `63855993600000000000`.

**Comment by JeffreySarnoff** [comment]
already in the docs/  here
<https://github.com/JuliaTime/NanoDates.jl/blob/main/docs/src/use/timestamps.md>
for some reason it did regenerate the docs with the improvements -- thanks
for the note

**Comment by JeffreySarnoff** [comment]
ok that worked the docs are regenerated
